# Generated by Django 2.2.2 on 2019-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_auto_20190619_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.PositiveIntegerField(choices=[(1, 'Normal'), (2, 'Fixed Defect'), (3, 'Reversable Defect')]),
        ),
    ]
