# Generated by Django 2.2.2 on 2019-06-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_auto_20190620_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.PositiveIntegerField(),
        ),
    ]
