# Generated by Django 2.2.2 on 2019-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_auto_20190620_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
