# Generated by Django 2.2.2 on 2019-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_auto_20190620_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.FloatField(),
        ),
    ]
