# Generated by Django 2.2.2 on 2019-07-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_auto_20190701_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.FloatField(db_column='Confidence(Percent)'),
        ),
    ]
