# Generated by Django 2.2.2 on 2019-07-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0007_auto_20190701_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.FloatField(db_column='target'),
        ),
    ]
