# Generated by Django 2.2.2 on 2019-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.PositiveIntegerField()),
                ('glucose', models.PositiveIntegerField()),
                ('blood_pressure', models.PositiveIntegerField()),
                ('skin_thickness', models.PositiveIntegerField()),
                ('insulin', models.PositiveIntegerField()),
                ('b_m_i', models.PositiveIntegerField()),
                ('diabetes_pedigree_function', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('outcome', models.FloatField()),
            ],
        ),
    ]
